#update_fastlane

default_platform(:android)
#  before_all do
#    f = File.open("../local.properties", "r")
#    ENV["SLACK_URL"] = f.each_line.to_a.last.split('=').last
#    f.close
#   end

  before_all do
    ENV["SLACK_URL"] = https://hooks.slack.com/services/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
  end

  desc "build the application"
  lane :playstore do
    gradle(
      task: "clean assembleRelease",
    )
  end

  after_all do |lane|
      slack(
        message: "Build successful"
      )
   end

   error do |lane, exception|
       slack(
         message: exception.message,
         success: false
         )
    end


